//
// Created by Matias Araya on 6/15/17.
//

#ifndef IA_SIMULATEDANNEALING_SIMULATEDANNEALING_H
#define IA_SIMULATEDANNEALING_SIMULATEDANNEALING_H


class SimulatedAnnealing {

};


#endif //IA_SIMULATEDANNEALING_SIMULATEDANNEALING_H
